### ISSUE TITLE
Ubuntu 14.04 package conflict: libtiff5-dev / libjpeg62-dev

### ISSUE THREAD

**Issue by tisto** [UPCnet/maxserver#1]
Installing the OS dependencies on Ubuntu 14.04 leads to package conflicts with libtiff5-dev and libjpeg62-dev.

```
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 libtiff5-dev : Hängt ab von: libjpeg-dev
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
```

(sorry for the German output)

**Comment by sunbit** [comment]
Fixed, changed failing dependencies for its metapackages
